version: 2
jobs:
  build:
    docker:
    - image: fbrissi/maven-openjfx:jdk-8
    working_directory: ~/app
    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-{{ checksum "pom.xml" }}
        - v1-
        paths:
        - ~/.m2

    - run:
        command: mvn -U test
        name: Running unit tests
        when: always
    - deploy:
        command: |
          mkdir -p target/junit/
          find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} target/junit/ \;
        name: Copy test artifacts
    - store_test_results:
        path: target/junit/
    - store_artifacts:
        path: target/junit/

    - deploy:
        command: mvn site -P report
        name: Building reports
    - store_artifacts:
        path: target/site/

    - deploy:
        command: mvn package -DskipTests
        name: Building .jar
    - run:
        command: |
          mkdir jar
          cp target/musicbot-desktop-*jar-with-dependencies.jar jar/musicbot-desktop.jar
        name: Renaming .jar
        when: on_success
    - store_artifacts:
        path: jar/

    - save_cache:
        key: v1-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2
